---
title: "Introduccion a R"
author: "Dayan Ochoa Oviedo"
date: "15/02/2023" 
output: pdf_document
---

## Operaciones basicas

Las operaciones de matematicas, logicas y de asignacion

$$
\hat{x} = \frac{x}{x}
$$

```{r}
x = c(1:10, NaN, 10:-20, NaN, 27)
xi = sum(x)/length(x)
xi
```
```{r vectores con datos}
x1 = c(1:10, NaN, 10:-20, NaN, 27)
x1i = sum(x1, na.rm = TRUE)/length(x1)
x1i
```



```{r}
x = c(1:100)
xi = sum(x)/length(x)
xi
```

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.16")

```

```{r}
#BiocManager::available()

```
###Manipulacion de datos
```{r tidy, echo=TRUE}
library(tidyverse); library(ggplot2)
data("diamonds")
plot(pressure)
#ctrl+shift+m para concatenar funciones
df1 = diamonds %>% ggplot(aes(x=depth, y=price, color=cut)) + geom_point(size=0.2) + facet_wrap(cut~.)
df1

df2= diamonds %>% ggplot(aes(x=cut, y=price, color=cut)) + geom_boxplot() + geom_jitter(size=0.1, alpha=0.2) + facet_wrap(clarity~.)
df2
```